using UnityEngine;

namespace MysticMap.World
{
    /// <summary>
    /// Tiny, fully deterministic integer hashing used by every procedural decision in the
    /// streamed world. Nothing here depends on platform, time, frame-rate or
    /// UnityEngine.Random, so the same (seed, coordinates) always yields the same world -
    /// in the editor, in a build, and on every machine. It never allocates.
    /// </summary>
    public static class DetHash
    {
        /// <summary>Avalanche/mixing step (a variant of the xxHash/murmur finalizer).</summary>
        public static uint Mix(uint x)
        {
            unchecked
            {
                x ^= x >> 16;
                x *= 0x7feb352dU;
                x ^= x >> 15;
                x *= 0x846ca68bU;
                x ^= x >> 16;
                return x;
            }
        }

        /// <summary>Hash of a single integer with a salt.</summary>
        public static uint Hash(int a, uint salt) => Mix(unchecked((uint)a * 0x9E3779B1U) ^ Mix(salt));

        /// <summary>Hash of two integers (a grid cell) with a salt.</summary>
        public static uint Hash(int a, int b, uint salt)
        {
            unchecked
            {
                uint h = Mix(salt ^ 0x51ED270BU);
                h = Mix(h ^ ((uint)a * 0x9E3779B1U));
                h = Mix(h ^ ((uint)b * 0x85EBCA77U));
                return h;
            }
        }

        /// <summary>Hash of three integers with a salt.</summary>
        public static uint Hash(int a, int b, int c, uint salt)
        {
            unchecked
            {
                uint h = Mix(Hash(a, b, salt) ^ ((uint)c * 0xC2B2AE3DU));
                return Mix(h);
            }
        }

        /// <summary>Deterministic float in [0, 1).</summary>
        public static float Float01(uint h) => (h >> 8) * (1f / 16777216f);

        /// <summary>Deterministic float in [-1, 1).</summary>
        public static float Signed(uint h) => Float01(h) * 2f - 1f;

        /// <summary>Deterministic float in [min, max).</summary>
        public static float Range(uint h, float min, float max) => min + (max - min) * Float01(h);

        /// <summary>Deterministic angle in radians, in [-PI, PI).</summary>
        public static float Angle(uint h) => Signed(h) * Mathf.PI;

        /// <summary>Deterministic bool that is true with the given probability.</summary>
        public static bool Chance(uint h, float probability) => Float01(h) < probability;

        /// <summary>Deterministic pick of an array index (returns -1 when the array is empty).</summary>
        public static int Pick(uint h, int count) => count <= 0 ? -1 : (int)(Float01(h) * count) % count;

        /// <summary>Deterministic pick from an array (null when the array is null/empty).</summary>
        public static T Pick<T>(uint h, T[] items) where T : class
        {
            if (items == null || items.Length == 0) return null;
            return items[(int)(Float01(h) * items.Length) % items.Length];
        }
    }

    /// <summary>
    /// A cheap deterministic random stream for one chunk / one site. Seeded from a handful
    /// of integers, so a chunk can be regenerated byte-for-byte at any time.
    /// </summary>
    public struct DetRandom
    {
        uint _state;

        public DetRandom(uint seed)
        {
            _state = seed == 0 ? 0x9E3779B9u : seed;
        }

        public DetRandom(int a, int b, uint salt)
        {
            _state = DetHash.Hash(a, b, salt) | 1u;
        }

        public uint NextUInt()
        {
            unchecked
            {
                // xorshift32 - fast, tiny state, good enough for scatter decisions.
                _state ^= _state << 13;
                _state ^= _state >> 17;
                _state ^= _state << 5;
                return _state;
            }
        }

        /// <summary>Next float in [0, 1).</summary>
        public float Next01() => (NextUInt() >> 8) * (1f / 16777216f);

        /// <summary>Next float in [-1, 1).</summary>
        public float NextSigned() => Next01() * 2f - 1f;

        public float Range(float min, float max) => min + (max - min) * Next01();

        public int Range(int minInclusive, int maxExclusive)
        {
            if (maxExclusive <= minInclusive) return minInclusive;
            return minInclusive + (int)(Next01() * (maxExclusive - minInclusive));
        }

        public bool Chance(float probability) => Next01() < probability;

        /// <summary>Random Y rotation in degrees.</summary>
        public float Yaw() => Next01() * 360f;

        public Vector2 OnUnitCircle()
        {
            float a = Next01() * Mathf.PI * 2f;
            return new Vector2(Mathf.Cos(a), Mathf.Sin(a));
        }

        public T Pick<T>(T[] items) where T : class
        {
            if (items == null || items.Length == 0) return null;
            return items[(int)(Next01() * items.Length) % items.Length];
        }
    }
}
